python inference/inference_video.py \
        --model-type mattingrefine \
        --model-backbone resnet50 \
        --model-backbone-scale 0.25 \
        --model-refine-mode sampling \
        --model-refine-sample-pixels 80000 \
        --model-checkpoint "/model/PyTorch/pytorch_resnet50.pth" \
        --video-src "/dataset/video/c3.mp4" \
        --video-bgr "/dataset/video/c3.png" \
        --output-dir "/result/" \
        --output-type com fgr pha err ref
